GET http://localhost:5043/games

###
GET http://localhost:5043/games/2

###
POST http://localhost:5043/games
Content-Type: application/json

{
  "name": "Ton",
  "genreId": 1,
  "price": 29.99,
  "releaseDate": "2026-11-15"
}

###
PUT http://localhost:5043/games/1
Content-Type: application/json

{
  "name": "Calypso Reborn",
  "genre": "Adventure RPG",
  "price": 59.99,
  "releaseDate": "2027-11-15"
}

###
DELETE http://localhost:5043/games/2